# -*- coding: utf-8 -*-
"""Lemmatization NLTK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6cZDDwJy8gfAQ4pdScfh55VMZWaT_4M
"""



"""Wordnet Lemmatizer  :

Lemmatization technique is like stemming.The o/p we ll get after lemmatization is called lemma.wich is a root word rather that root stem , the o/p of stemming.after lemmatization we ll be getting a valid word that means the same thing.


NLTK provides WordNetLemmatization class which is a thin wrapper around the wordnet corpus.this class uses morphy() function to the WordNet corpusReader class to find a lemma
"""

import nltk

nltk.download('wordnet')

## Q&A , chatbot,textsummerization

lemmatizer=WordNetLemmatizer()

lemmatizer.lemmatize("going",pos='v')

words=["eating","eats","ate","eat","writting","programming","history","finally"]


for word in words:
  print(word+"---->"+lemmatizer.lemmatize(word,pos='v'))

lemmatizer.lemmatize("goes",pos='v')

