# -*- coding: utf-8 -*-
"""Stemming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahpLUQa5CHNaWZ4y7qKJ6CljBwYlB3kO

stemming os the process of reducing a wor to its word stem that affixes to suffixes and prefixes or the roots of the word is known as lemma. Stemming is imp in natural  lang.understing(NLU) and NLP
"""

# CLASSIFCATION PROBLEM
#comment of product is positive or negative review
# Review-----> eating,eat,eaten

words=["eating","eats","ate","eat","writting","programming","history","finally"]



"""# Stemming Technique"""



"""PorterStemmer"""

from nltk.stem import PorterStemmer

stemming=PorterStemmer()

for word in words:
  print(word+"---->"+stemming.stem(word))

stemming.stem("congratuation")

stemming.stem("setting")

"""RegexpStemmer class   :

NLTK has RegexpStemer class with the help of which we can easily implement regular expression stemer algoriths.It basically takes  sigle regular expression and removes any prefix or suffix that matches the expression
"""

from nltk.stem import RegexpStemmer

reg_stemmer=RegexpStemmer('ing$|s$|e$|able$', min=4)

reg_stemmer.stem("eating")

reg_stemmer.stem("ingeating")

"""# Snowball Stemmer"""

from nltk.stem import SnowballStemmer

snowballstemmer=SnowballStemmer("english")

for word in words:
  print(word+"---->"+snowballstemmer.stem(word))

stemming.stem("fairly"),stemming.stem("sportingly")

snowballstemmer.stem("fairly"),snowballstemmer.stem("sportingly")

